/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DecisionsIndexRouteImport } from './routes/decisions/index'
import { Route as DecisionsDecisionIdRouteImport } from './routes/decisions/$decisionId'
import { Route as DecisionsNewRouteImport } from './routes/decisions/new'
import { Route as ModulesIndexRouteImport } from './routes/modules/index'
import { Route as ModulesModuleIdRouteImport } from './routes/modules/$moduleId'
import { Route as ModulesNewRouteImport } from './routes/modules/new'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as RepositoriesRepositoryIdRouteImport } from './routes/repositories/$repositoryId'
import { Route as RepositoriesNewRouteImport } from './routes/repositories/new'
import { Route as ReviewsDailyRouteImport } from './routes/reviews/daily'
import { Route as ReviewsWeeklyRouteImport } from './routes/reviews/weekly'
import { Route as StandardsIndexRouteImport } from './routes/standards/index'
import { Route as StandardsStandardIdRouteImport } from './routes/standards/$standardId'
import { Route as StandardsNewRouteImport } from './routes/standards/new'
import { Route as StandardsStandardIdEditRouteImport } from './routes/standards/$standardId.edit'
import { Route as ModulesModuleIdReleasesNewRouteImport } from './routes/modules/$moduleId/releases/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsIndexRoute = DecisionsIndexRouteImport.update({
  id: '/decisions/',
  path: '/decisions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsDecisionIdRoute = DecisionsDecisionIdRouteImport.update({
  id: '/decisions/$decisionId',
  path: '/decisions/$decisionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsNewRoute = DecisionsNewRouteImport.update({
  id: '/decisions/new',
  path: '/decisions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesNewRoute = ModulesNewRouteImport.update({
  id: '/modules/new',
  path: '/modules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRepositoryIdRoute =
  RepositoriesRepositoryIdRouteImport.update({
    id: '/repositories/$repositoryId',
    path: '/repositories/$repositoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesNewRoute = RepositoriesNewRouteImport.update({
  id: '/repositories/new',
  path: '/repositories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsDailyRoute = ReviewsDailyRouteImport.update({
  id: '/reviews/daily',
  path: '/reviews/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsWeeklyRoute = ReviewsWeeklyRouteImport.update({
  id: '/reviews/weekly',
  path: '/reviews/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsIndexRoute = StandardsIndexRouteImport.update({
  id: '/standards/',
  path: '/standards/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsStandardIdRoute = StandardsStandardIdRouteImport.update({
  id: '/standards/$standardId',
  path: '/standards/$standardId',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsNewRoute = StandardsNewRouteImport.update({
  id: '/standards/new',
  path: '/standards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsStandardIdEditRoute = StandardsStandardIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StandardsStandardIdRoute,
} as any)
const ModulesModuleIdReleasesNewRoute =
  ModulesModuleIdReleasesNewRouteImport.update({
    id: '/releases/new',
    path: '/releases/new',
    getParentRoute: () => ModulesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/decisions/new': typeof DecisionsNewRoute
  '/modules/$moduleId': typeof ModulesModuleIdRouteWithChildren
  '/modules/new': typeof ModulesNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/reviews/daily': typeof ReviewsDailyRoute
  '/reviews/weekly': typeof ReviewsWeeklyRoute
  '/standards/$standardId': typeof StandardsStandardIdRouteWithChildren
  '/standards/new': typeof StandardsNewRoute
  '/decisions/': typeof DecisionsIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/standards/$standardId/edit': typeof StandardsStandardIdEditRoute
  '/modules/$moduleId/releases/new': typeof ModulesModuleIdReleasesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/decisions/new': typeof DecisionsNewRoute
  '/modules/$moduleId': typeof ModulesModuleIdRouteWithChildren
  '/modules/new': typeof ModulesNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/reviews/daily': typeof ReviewsDailyRoute
  '/reviews/weekly': typeof ReviewsWeeklyRoute
  '/standards/$standardId': typeof StandardsStandardIdRouteWithChildren
  '/standards/new': typeof StandardsNewRoute
  '/decisions': typeof DecisionsIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/standards': typeof StandardsIndexRoute
  '/standards/$standardId/edit': typeof StandardsStandardIdEditRoute
  '/modules/$moduleId/releases/new': typeof ModulesModuleIdReleasesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/decisions/new': typeof DecisionsNewRoute
  '/modules/$moduleId': typeof ModulesModuleIdRouteWithChildren
  '/modules/new': typeof ModulesNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/reviews/daily': typeof ReviewsDailyRoute
  '/reviews/weekly': typeof ReviewsWeeklyRoute
  '/standards/$standardId': typeof StandardsStandardIdRouteWithChildren
  '/standards/new': typeof StandardsNewRoute
  '/decisions/': typeof DecisionsIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/standards/$standardId/edit': typeof StandardsStandardIdEditRoute
  '/modules/$moduleId/releases/new': typeof ModulesModuleIdReleasesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/decisions/$decisionId'
    | '/decisions/new'
    | '/modules/$moduleId'
    | '/modules/new'
    | '/products/$productId'
    | '/products/new'
    | '/repositories/$repositoryId'
    | '/repositories/new'
    | '/reviews/daily'
    | '/reviews/weekly'
    | '/standards/$standardId'
    | '/standards/new'
    | '/decisions/'
    | '/modules/'
    | '/products/'
    | '/repositories/'
    | '/standards/'
    | '/standards/$standardId/edit'
    | '/modules/$moduleId/releases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/decisions/$decisionId'
    | '/decisions/new'
    | '/modules/$moduleId'
    | '/modules/new'
    | '/products/$productId'
    | '/products/new'
    | '/repositories/$repositoryId'
    | '/repositories/new'
    | '/reviews/daily'
    | '/reviews/weekly'
    | '/standards/$standardId'
    | '/standards/new'
    | '/decisions'
    | '/modules'
    | '/products'
    | '/repositories'
    | '/standards'
    | '/standards/$standardId/edit'
    | '/modules/$moduleId/releases/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/decisions/$decisionId'
    | '/decisions/new'
    | '/modules/$moduleId'
    | '/modules/new'
    | '/products/$productId'
    | '/products/new'
    | '/repositories/$repositoryId'
    | '/repositories/new'
    | '/reviews/daily'
    | '/reviews/weekly'
    | '/standards/$standardId'
    | '/standards/new'
    | '/decisions/'
    | '/modules/'
    | '/products/'
    | '/repositories/'
    | '/standards/'
    | '/standards/$standardId/edit'
    | '/modules/$moduleId/releases/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  DecisionsDecisionIdRoute: typeof DecisionsDecisionIdRoute
  DecisionsNewRoute: typeof DecisionsNewRoute
  ModulesModuleIdRoute: typeof ModulesModuleIdRouteWithChildren
  ModulesNewRoute: typeof ModulesNewRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  RepositoriesRepositoryIdRoute: typeof RepositoriesRepositoryIdRoute
  RepositoriesNewRoute: typeof RepositoriesNewRoute
  ReviewsDailyRoute: typeof ReviewsDailyRoute
  ReviewsWeeklyRoute: typeof ReviewsWeeklyRoute
  StandardsStandardIdRoute: typeof StandardsStandardIdRouteWithChildren
  StandardsNewRoute: typeof StandardsNewRoute
  DecisionsIndexRoute: typeof DecisionsIndexRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  StandardsIndexRoute: typeof StandardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/': {
      id: '/decisions/'
      path: '/decisions'
      fullPath: '/decisions/'
      preLoaderRoute: typeof DecisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$decisionId': {
      id: '/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof DecisionsDecisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/new': {
      id: '/decisions/new'
      path: '/decisions/new'
      fullPath: '/decisions/new'
      preLoaderRoute: typeof DecisionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/new': {
      id: '/modules/new'
      path: '/modules/new'
      fullPath: '/modules/new'
      preLoaderRoute: typeof ModulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId': {
      id: '/repositories/$repositoryId'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof RepositoriesRepositoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/new': {
      id: '/repositories/new'
      path: '/repositories/new'
      fullPath: '/repositories/new'
      preLoaderRoute: typeof RepositoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/daily': {
      id: '/reviews/daily'
      path: '/reviews/daily'
      fullPath: '/reviews/daily'
      preLoaderRoute: typeof ReviewsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/weekly': {
      id: '/reviews/weekly'
      path: '/reviews/weekly'
      fullPath: '/reviews/weekly'
      preLoaderRoute: typeof ReviewsWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/': {
      id: '/standards/'
      path: '/standards'
      fullPath: '/standards/'
      preLoaderRoute: typeof StandardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/$standardId': {
      id: '/standards/$standardId'
      path: '/standards/$standardId'
      fullPath: '/standards/$standardId'
      preLoaderRoute: typeof StandardsStandardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/new': {
      id: '/standards/new'
      path: '/standards/new'
      fullPath: '/standards/new'
      preLoaderRoute: typeof StandardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/$standardId/edit': {
      id: '/standards/$standardId/edit'
      path: '/edit'
      fullPath: '/standards/$standardId/edit'
      preLoaderRoute: typeof StandardsStandardIdEditRouteImport
      parentRoute: typeof StandardsStandardIdRoute
    }
    '/modules/$moduleId/releases/new': {
      id: '/modules/$moduleId/releases/new'
      path: '/releases/new'
      fullPath: '/modules/$moduleId/releases/new'
      preLoaderRoute: typeof ModulesModuleIdReleasesNewRouteImport
      parentRoute: typeof ModulesModuleIdRoute
    }
  }
}

interface ModulesModuleIdRouteChildren {
  ModulesModuleIdReleasesNewRoute: typeof ModulesModuleIdReleasesNewRoute
}

const ModulesModuleIdRouteChildren: ModulesModuleIdRouteChildren = {
  ModulesModuleIdReleasesNewRoute: ModulesModuleIdReleasesNewRoute,
}

const ModulesModuleIdRouteWithChildren = ModulesModuleIdRoute._addFileChildren(
  ModulesModuleIdRouteChildren,
)

interface StandardsStandardIdRouteChildren {
  StandardsStandardIdEditRoute: typeof StandardsStandardIdEditRoute
}

const StandardsStandardIdRouteChildren: StandardsStandardIdRouteChildren = {
  StandardsStandardIdEditRoute: StandardsStandardIdEditRoute,
}

const StandardsStandardIdRouteWithChildren =
  StandardsStandardIdRoute._addFileChildren(StandardsStandardIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  DecisionsDecisionIdRoute: DecisionsDecisionIdRoute,
  DecisionsNewRoute: DecisionsNewRoute,
  ModulesModuleIdRoute: ModulesModuleIdRouteWithChildren,
  ModulesNewRoute: ModulesNewRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  RepositoriesRepositoryIdRoute: RepositoriesRepositoryIdRoute,
  RepositoriesNewRoute: RepositoriesNewRoute,
  ReviewsDailyRoute: ReviewsDailyRoute,
  ReviewsWeeklyRoute: ReviewsWeeklyRoute,
  StandardsStandardIdRoute: StandardsStandardIdRouteWithChildren,
  StandardsNewRoute: StandardsNewRoute,
  DecisionsIndexRoute: DecisionsIndexRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  StandardsIndexRoute: StandardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
