/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModulesIndexRouteImport } from './routes/modules/index'
import { Route as ModulesModuleIdRouteImport } from './routes/modules/$moduleId'
import { Route as ModulesNewRouteImport } from './routes/modules/new'
import { Route as ModulesModuleIdReleasesNewRouteImport } from './routes/modules/$moduleId/releases/new'

const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesNewRoute = ModulesNewRouteImport.update({
  id: '/modules/new',
  path: '/modules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdReleasesNewRoute =
  ModulesModuleIdReleasesNewRouteImport.update({
    id: '/releases/new',
    path: '/releases/new',
    getParentRoute: () => ModulesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/modules/$moduleId': typeof ModulesModuleIdRouteWithChildren
  '/modules/new': typeof ModulesNewRoute
  '/modules/': typeof ModulesIndexRoute
  '/modules/$moduleId/releases/new': typeof ModulesModuleIdReleasesNewRoute
}
export interface FileRoutesByTo {
  '/modules/$moduleId': typeof ModulesModuleIdRouteWithChildren
  '/modules/new': typeof ModulesNewRoute
  '/modules': typeof ModulesIndexRoute
  '/modules/$moduleId/releases/new': typeof ModulesModuleIdReleasesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/modules/$moduleId': typeof ModulesModuleIdRouteWithChildren
  '/modules/new': typeof ModulesNewRoute
  '/modules/': typeof ModulesIndexRoute
  '/modules/$moduleId/releases/new': typeof ModulesModuleIdReleasesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/modules/$moduleId'
    | '/modules/new'
    | '/modules/'
    | '/modules/$moduleId/releases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/modules/$moduleId'
    | '/modules/new'
    | '/modules'
    | '/modules/$moduleId/releases/new'
  id:
    | '__root__'
    | '/modules/$moduleId'
    | '/modules/new'
    | '/modules/'
    | '/modules/$moduleId/releases/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ModulesModuleIdRoute: typeof ModulesModuleIdRouteWithChildren
  ModulesNewRoute: typeof ModulesNewRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/new': {
      id: '/modules/new'
      path: '/modules/new'
      fullPath: '/modules/new'
      preLoaderRoute: typeof ModulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId/releases/new': {
      id: '/modules/$moduleId/releases/new'
      path: '/releases/new'
      fullPath: '/modules/$moduleId/releases/new'
      preLoaderRoute: typeof ModulesModuleIdReleasesNewRouteImport
      parentRoute: typeof ModulesModuleIdRoute
    }
  }
}

interface ModulesModuleIdRouteChildren {
  ModulesModuleIdReleasesNewRoute: typeof ModulesModuleIdReleasesNewRoute
}

const ModulesModuleIdRouteChildren: ModulesModuleIdRouteChildren = {
  ModulesModuleIdReleasesNewRoute: ModulesModuleIdReleasesNewRoute,
}

const ModulesModuleIdRouteWithChildren = ModulesModuleIdRoute._addFileChildren(
  ModulesModuleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ModulesModuleIdRoute: ModulesModuleIdRouteWithChildren,
  ModulesNewRoute: ModulesNewRoute,
  ModulesIndexRoute: ModulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
